PermitUserEnvironment no

Match User warpmetal-sandbox
    AuthorizedKeysFile /etc/ssh/warpmetal-runtime/authorized_keys
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PubkeyAuthentication yes
    DisableForwarding yes
    AllowAgentForwarding no
    AllowTcpForwarding no
    AllowStreamLocalForwarding no
    PermitTunnel no
    GatewayPorts no
    X11Forwarding no
    PermitUserRC no
    PermitTTY yes

Match all
