Match User warpmetal-sandbox
    AuthorizedKeysFile /etc/ssh/warpmetal_sandbox_authorized_keys
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PubkeyAuthentication yes
    DisableForwarding yes
    AllowAgentForwarding no
    AllowTcpForwarding no
    AllowStreamLocalForwarding no
    PermitTunnel no
    GatewayPorts no
    X11Forwarding no
    PermitUserEnvironment no
    PermitUserRC no
    PermitTTY yes

Match all
